name: Continuous

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: Push'
        run: ./build.cmd Push
        env:
          FeedGitHubToken: ${{ secrets.FEED_GITHUB_TOKEN }}
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
      - name: Report Coveralls
        uses: coverallsapp/github-action@v2
      - name: 'Publish: Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: Artifacts
